# ============================================================
# Stage 1 — Builder
# Installs all workspace dependencies and produces the Next.js
# standalone bundle at apps/web/.next/standalone.
# ============================================================
FROM node:22-slim AS builder

# Enable pnpm via corepack (ships with Node 22).
RUN corepack enable && corepack prepare pnpm@11.0.3 --activate

WORKDIR /build

# Copy workspace manifests first so Docker can cache the install
# layer as long as lock files haven't changed.
COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
COPY packages/core/package.json ./packages/core/
COPY apps/web/package.json       ./apps/web/

# Install all workspace deps (frozen — same versions as lock file).
RUN pnpm install --frozen-lockfile

# Copy remaining source code.
COPY packages/core/ ./packages/core/
COPY apps/web/       ./apps/web/

# Build the Next.js app.  next.config.ts sets output:'standalone',
# which emits a self-contained server at apps/web/.next/standalone.
RUN pnpm --filter web build


# ============================================================
# Stage 2 — Runner
# Minimal image: only the standalone bundle + runtime deps.
# ============================================================
FROM node:22-slim AS runner

# --- System runtime dependencies --------------------------------

# poppler-utils: provides pdftotext + pdftoppm, used by /api/cv/extract
#                (and the screenshot fallback) and the ATS validator.
# python3:       runs apps/web/tools/ats/validate_ats.py.
# xz-utils:      provides `xz`, required by `tar -xJ` to unpack the
#                Typst .tar.xz release below (node:22-slim omits it).
RUN apt-get update && apt-get install -y --no-install-recommends \
        poppler-utils \
        python3 \
        xz-utils \
        curl \
        ca-certificates \
        fonts-roboto \
    && rm -rf /var/lib/apt/lists/*

# typst: document renderer for CV/resume PDF export.
# We download the official pre-built binary for linux-x86_64.
# Pin to a specific release so the build is reproducible.
ARG TYPST_VERSION=0.13.1
RUN curl -fsSL \
        "https://github.com/typst/typst/releases/download/v${TYPST_VERSION}/typst-x86_64-unknown-linux-musl.tar.xz" \
    | tar -xJ --strip-components=1 -C /usr/local/bin \
        "typst-x86_64-unknown-linux-musl/typst" \
    && chmod +x /usr/local/bin/typst \
    # Smoke-test the binary.
    && typst --version

# Pre-cache the Typst packages used by the modern-cv template so the container
# never needs network access at export time.  The compile step downloads
# modern-cv:0.9.0 and its transitive deps (fontawesome, linguify) during import
# resolution; a content/font error is tolerated (|| true) because the packages
# are already cached by the time any content error fires.  The find assertions
# confirm the packages actually landed — a build-time network failure makes the
# image build fail loudly rather than silently shipping a broken container.
RUN printf '#import "@preview/modern-cv:0.9.0": *\n#show: resume.with(author: (firstname: "Warm", lastname: "Up"))\nReady.\n' > /tmp/warm.typ \
    && (typst compile /tmp/warm.typ /tmp/warm.pdf || true) \
    && rm -f /tmp/warm.typ /tmp/warm.pdf \
    && find / -path '*packages/preview/modern-cv/0.9.0/typst.toml' -print -quit | grep -q . \
    && find / -path '*packages/preview/fontawesome/*/typst.toml' -print -quit | grep -q .

# ---------------------------------------------------------------

WORKDIR /app

# Copy the standalone Next.js server bundle (includes all required
# node_modules already traced by Next.js).
COPY --from=builder /build/apps/web/.next/standalone ./

# Copy static assets that Next.js standalone does NOT bundle.
# .next/static  → client-side JS chunks, CSS
# public/       → favicon, images, etc.
COPY --from=builder /build/apps/web/.next/static  ./apps/web/.next/static
COPY --from=builder /build/apps/web/public        ./apps/web/public

# Copy server-side resources used at runtime.
# templates/ — Typst .typ template files for PDF generation.
# tools/ats/ — Python ATS validator script.
COPY --from=builder /build/apps/web/templates ./apps/web/templates
COPY --from=builder /build/apps/web/tools     ./apps/web/tools

# Create the persistent data directory.
# In Coolify, mount a named volume to this path so data (runs,
# usage counters, exports) survives container restarts.
RUN mkdir -p /app/apps/web/.ghosted-local
VOLUME /app/apps/web/.ghosted-local

# The standalone server listens on port 3000 by default.
EXPOSE 3000

# Env vars that Next.js standalone reads.
ENV NODE_ENV=production \
    PORT=3000 \
    HOSTNAME=0.0.0.0 \
    # Tell the server where its working directory is so relative
    # paths (.ghosted-local, templates, tools) resolve correctly.
    NEXT_TELEMETRY_DISABLED=1

# The standalone entry point generated by Next.js.
CMD ["node", "apps/web/server.js"]
